version: '3.3'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/freelancer-messager
    command: bash -c "bin/setup && rails server -b 0.0.0.0 -p 4000"
    env_file:
      - .env
    ports:
      - "4000:4000"
    environment:
      TZ: Sao_Paulo/Sao_Paulo
    depends_on:
      - db
    networks:
      - hiring
      - db_network

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      TZ: Sao_Paulo/Sao_Paulo
    networks:
      - db_network
    

networks:
  hiring: 
    external: true
  db_network:
    external: false